<!-- GitHub Star -->
<a class="github-button" href="https://github.com/lets-blade/blade" data-count-href="/lets-blade/blade/stargazers" data-count-api="/repos/lets-blade/blade#stargazers_count" data-count-aria-label="# stargazers on GitHub" aria-label="Star lets-blade/blade on GitHub">Star</a>
<!-- GitHub fork -->
<a class="github-button" href="https://github.com/lets-blade/blade/fork" data-count-href="/lets-blade/blade/network" data-count-api="/repos/lets-blade/blade#forks_count" data-count-aria-label="# forks on GitHub" aria-label="Fork lets-blade/blade on GitHub">Fork</a>
